version: '3.8'

services:
  # 1. YOUR APP
  flashsale-app:
    build: .
    container_name: flashsale-app
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redis
    environment:
      # We use the container names to talk to other services now!
      SPRING_DATA_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/flashsale
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      # Note: 'host.docker.internal' lets Docker talk to your Windows Postgres.
      # If you moved Postgres to Docker too, this would be 'postgres-db'.

  # 2. REDIS
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # 3. ZOOKEEPER (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 4. KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # This complex networking block allows Kafka to be reached
      # by the App (internally) and by You (externally)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1